# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretAgent < Formula
  desc "YAML-defined chat bot with pluggable transports (CLI, Signal, Slack)"
  homepage "https://github.com/jtarchie/secret-agent"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/secret-agent/releases/download/v0.1.2/secret-agent_0.1.2_darwin_amd64.tar.gz"
      sha256 "284f2f4c3ec0dcd47365f728b9b643aaf3e6ee4dfba4c72756fcda4bb749af37"

      define_method(:install) do
        bin.install "secret-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/secret-agent/releases/download/v0.1.2/secret-agent_0.1.2_darwin_arm64.tar.gz"
      sha256 "e4baf1c8c2a76329025ce31fefd0af1cad426a3fe154548979e9b4645f63c917"

      define_method(:install) do
        bin.install "secret-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/secret-agent/releases/download/v0.1.2/secret-agent_0.1.2_linux_amd64.tar.gz"
      sha256 "7f4ea5be70b0c2cfbd88fc3720571a55095b7de046b6bd11f82959bd641cadd7"
      define_method(:install) do
        bin.install "secret-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/secret-agent/releases/download/v0.1.2/secret-agent_0.1.2_linux_arm64.tar.gz"
      sha256 "02a997adbd95d92b5d48c0b0d58aefea66e5106b0320dfa40f9b02213fe32482"
      define_method(:install) do
        bin.install "secret-agent"
      end
    end
  end

  test do
    system "#{bin}/secret-agent", "--help"
  end
end
